---
- name: Install MariaDB server packages
  yum: name={{ packages }} state=present
  vars:
    packages:
      - MariaDB-client
      - MariaDB-server
      - galera

- name: Install percona-xtrabackup packages
  yum: name={{ packages }} state=present
  vars:
    packages:
      - percona-xtrabackup
      - socat
  when: "mariadb_release | version_compare('10.2', '<')"

- name: Install MariaDB-backup packages
  yum: name={{ packages }} state=present
  vars:
    packages:
      - MariaDB-backup
      - socat
  when: "mariadb_release | version_compare('10.2', '>=')"

- name: Install MySQL-python
  yum: name=MySQL-python state=present
